# HTTP helpers that expose gcry metrics (JSON + Prometheus).
# Use under `-Dgc_none` after `require "gcry"`.
#
#   get "/metrics" { Gcry.prometheus_text }
#   get "/gc-stats" { Gcry::Observability.json_stats }

require "json"

module Gcry
  module Observability
    # Full dogfood snapshot (same fields as historical Kemal `/gc-stats`).
    def self.json_stats(heap : Heap = Gcry.default_heap) : String
      p = PauseStats.new(
        heap.last_pause_ns,
        heap.max_pause_ns,
        heap.total_pause_ns,
        heap.pause_count,
        heap.pause_percentile_ns(50.0),
        heap.pause_percentile_ns(99.0),
      )
      {
        collections:                  heap.collections,
        major_collections:            heap.major_collections,
        minor_collections:            heap.minor_collections,
        heap_size:                    heap.heap_size,
        free_bytes:                   heap.free_bytes,
        bytes_since_gc:               heap.bytes_since_gc,
        unmapped_bytes:               heap.unmapped_bytes,
        live_objects:                 heap.live_objects,
        pause_count:                  p.count,
        pause_last_ns:                p.last_ns,
        pause_p50_ns:                 p.p50_ns,
        pause_p99_ns:                 p.p99_ns,
        pause_max_ns:                 p.max_ns,
        pause_total_ns:               p.total_ns,
        phase_clear_ns:               heap.last_phase_clear_ns,
        phase_scrub_ns:               heap.last_phase_scrub_ns,
        header_mark_gen:              heap.header_mark_gen.to_u64,
        header_mark_gen_full_clears:  heap.header_mark_gen_full_clears,
        phase_roots_ns:               heap.last_phase_roots_ns,
        phase_static_ns:              heap.last_phase_static_ns,
        phase_stacks_ns:              heap.last_phase_stacks_ns,
        phase_mark_ns:                heap.last_phase_mark_ns,
        phase_sweep_ns:               heap.last_phase_sweep_ns,
        phase_post_stw_wait_ns:       heap.last_phase_post_stw_wait_ns,
        phase_stw_stop_ns:            heap.last_phase_stw_stop_ns,
        phase_stw_start_ns:           heap.last_phase_stw_start_ns,
        phase_flush_ns:               heap.last_phase_flush_ns,
        max_post_stw_wait_ns:         heap.max_post_stw_wait_ns,
        post_stw_wait_total_ns:       heap.post_stw_wait_total_ns,
        post_stw_wait_count:          heap.post_stw_wait_count,
        collect_coalesced:            heap.collect_coalesced,
        large_free_bytes:             heap.large_free_bytes,
        large_mapped_bytes:           heap.large_mapped_bytes,
        small_mapped_bytes:           heap.small_mapped_bytes,
        small_free_bytes:             heap.small_free_bytes,
        large_cache_retain:           heap.large_cache_retain,
        size_class_chunk_count:       heap.size_class_chunk_count,
        fully_free_chunk_bytes:       heap.fully_free_chunk_bytes,
        released_chunk_bytes:         heap.released_chunk_bytes,
        size_class_live_bytes:        heap.size_class_live_bytes,
        chunk_fill_lt25:              heap.chunk_fill_lt25,
        chunk_fill_lt50:              heap.chunk_fill_lt50,
        chunk_fill_lt75:              heap.chunk_fill_lt75,
        chunk_fill_ge75:              heap.chunk_fill_ge75,
        small_chunk_bytes:            heap.small_chunk_bytes,
        soft_dirty_armed:             heap.soft_dirty_armed?,
        soft_dirty_page_scans:        heap.soft_dirty_page_scans,
        soft_dirty_fallbacks:         heap.soft_dirty_fallbacks,
        soft_dirty_last_dirty:        heap.last_soft_dirty_pages,
        soft_dirty_last_total:        heap.last_soft_dirty_total,
        soft_dirty_max_pct:           heap.soft_dirty_max_pct,
        dormant_chunk_bytes:          heap.dormant_chunk_bytes,
        sweep_dormant_skips:          heap.sweep_dormant_skips,
        dontneed_bytes:               heap.dontneed_bytes,
        empty_chunk_retain:           heap.empty_chunk_retain,
        empty_chunk_warm_retain:      heap.empty_chunk_warm_retain,
        layout_precise_scans:         heap.layout_precise_scans,
        layout_conservative_scans:    heap.layout_conservative_scans,
        precise_stack_roots:          heap.precise_stack_roots,
        precise_stack_exclusive:      heap.precise_stack_exclusive,
        precise_stack_roots_marked:   heap.precise_stack_roots_marked,
        stack_maps_loaded:            StackMaps.loaded?,
        stack_maps_records:           StackMaps.record_count,
        stack_maps_hits:              StackMaps.hits,
        stack_maps_near_hits:         StackMaps.near_hits,
        stack_maps_lookups:           StackMaps.lookups,
        stack_maps_roots_yielded:     StackMaps.roots_yielded,
        layout_entries:               Layout.size,
        layout_unsafe_skips:          Layout.unsafe_skips_count,
        type_id_root_rejects:         heap.type_id_root_rejects,
        type_id_stack_rejects:        heap.type_id_stack_rejects,
        type_id_static_rejects:       heap.type_id_static_rejects,
        type_id_thread_rejects:       heap.type_id_thread_rejects,
        type_id_root_false_negatives: heap.type_id_root_false_negatives,
        sp_clamp_hits:                heap.sp_clamp_hits,
        sp_clamp_fallbacks:           heap.sp_clamp_fallbacks,
        finalizer_entries:            heap.finalizer_entry_count,
        weak_links:                   heap.finalizer_link_count,
        blacklist_hits:               heap.blacklist_hits,
        blacklist_skips:              heap.blacklist_skips,
        tlab_refills:                 heap.tlab_refills,
        tlab_steals:                  heap.tlab_steals,
        tlab_hits:                    heap.tlab_hits,
        tlab_hit_rate_pct:            heap.tlab_refills + heap.tlab_hits > 0 ? (heap.tlab_hits * 100) // (heap.tlab_refills + heap.tlab_hits) : 100_u64,
        alloc_batch:                  heap.alloc_batch,
        alloc_batch_hits:             heap.alloc_batch_hits,
        alloc_batch_refills:          heap.alloc_batch_refills,
        parallel_mark_workers:        heap.parallel_mark_workers,
        parallel_mark_runs:           heap.parallel_mark_runs,
        parallel_mark_stolen:         heap.parallel_mark_stolen,
        clear_stack_calls:            heap.clear_stack_calls,
        clear_stack_bytes_total:      heap.clear_stack_bytes_total,
        fiber_scrub_bytes:            heap.fiber_scrub_bytes,
        fiber_scrub_runs:             heap.fiber_scrub_runs,
        fiber_scrub_bytes_total:      heap.fiber_scrub_bytes_total,
        barrier_backend:              heap.barrier_backend_name,
        barrier_dirty_rescans:        heap.barrier_dirty_rescans,
        nursery_survival_bytes:       heap.nursery_survival_bytes,
        nursery_alloc_before_minor:   heap.nursery_alloc_before_minor,
        nursery_survival_rate_pct:    heap.nursery_survival_rate_pct,
        adaptive_nursery:             heap.adaptive_nursery,
      }.to_json
    end

    def self.prometheus(heap : Heap = Gcry.default_heap, prefix : String = "gcry") : String
      Gcry.prometheus_text(heap, prefix)
    end
  end
end
